- name: mkdir /etc/keepalived
  shell: mkdir /etc/keepalived 
  ignore_errors: True

- name: generate keepalived configuration
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf backup=yes

- name: generate keepalived init.d
  shell: creates=/etc/init.d/keepalived cp /usr/local/webserver/keepalived/etc/rc.d/init.d/keepalived /etc/init.d/ 

- name: /etc/sysconfig/ 
  shell: creates=/etc/sysconfig/keepalived cp /usr/local/webserver/keepalived/etc/sysconfig/keepalived /etc/sysconfig/

- name: copy sbin
  shell: creates=/usr/sbin/keepalived cp /usr/local/webserver/keepalived/sbin/keepalived /usr/sbin/

- name: add keepalived start on boot
  service: name=keepalived enabled=yes
